tidymodels/yardstick

tests/testthat/test_class.R, tests/testthat/test_metrics.R, tests/testthat/test_regression.R, tests/testthat/test_regression_extra.R, tests/testthat/test_selectors.R, tests/testthat/test_two_class.R
Fixes #22.
Looks like RStudio also cut some excess whitespace from the end of some lines; hope that's alright, happy to undo those if not.
=> Add context() to top of each test file.

R/template.R, tests/testthat/test_two_class.R
If `na.rm = FALSE`, this was not respected in classification metrics b/c of the default behavior of `table()` as documented in #41. This PR fixes this by exiting early from the metric function if any NA values are encountered.
=> Fix/respect na.rm

NEWS.md, R/aaa.R, R/conf_mat.R, man/conf_mat.Rd, tests/testthat/test_autoplot.R
I gave a shot at #10, I couldn't decide between the standardly used heatmap and the mosaic plot so I added both.
``` r
library(tidymodels)
cm_small <- conf_mat(two_class_example, truth, predicted)
cm_big <- hpc_cv %>%
filter(Resample == "Fold01") %>%
conf_mat(obs, pred)
autoplot(cm_small)
```
``` r
autoplot(cm_big)
```
``` r
autoplot(cm_small, type = "heatmap")
```
``` r
autoplot(cm_big, type = "heatmap")
```
<sup>Created on 2019-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
with the standard ggplot-ness scales can be changed again
``` r
autoplot(cm_small, type = "heatmap") +
scale_fill_gradient(low = "white", high = "darkred")
```
<sup>Created on 2019-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
=> adding autoplot method for conf_mat

NEWS.md, R/class-f_meas.R, tests/testthat/test-class-f_meas.R
=> Ensure that `f_meas()` propagates `NA` values from `precision()` and `recall()`.

R/metrics.R, R/selectors.R
I noticed that `metrics()` was the only function that didn't validate the `truth` and `estimate` argument, so I added tests using the helper function `validate_not_missing()`.
=> missing validation in metrics

DESCRIPTION, R/prob-roc_curve.R, tests/testthat/test-prob-roc.R
An upcoming version of pROC (1.16) will feature backward incompatible changes in the coords function. In order to adhere to the principles of tidy datasets, the output will be transposed, and a data.frame returned instead of a matrix.
This PR sets the 'transpose' argument to 'coords' explicitly, and ensures proper operation with current (1.15) and future versions of pROC.
=> Use tidy version of coords (xrobin/pROC#54)

R/metrics.R, man/metrics.Rd
- `metrics()` appears to return a *three* column tibble with columns {`.metric`, .`estimator`, and .`estimate`}
=> document that metrics() returns 3 column tibble

NEWS.md, R/prob-roc_auc.R, R/prob-roc_aunp.R, R/prob-roc_aunu.R, R/prob-roc_curve.R, man/conf_mat.Rd, man/metrics.Rd, man/roc_auc.Rd, man/roc_aunp.Rd, man/roc_aunu.Rd, man/roc_curve.Rd, tests/testthat/test-prob-roc.R
Closes #123 
This PR fixes two issues:
---
The first was a long standing bug, which has been around since day 1 when `pr_auc()` was implemented on top of `pROC::auc()` (and through it, `pROC::roc()`). It affected binary pr-auc and the multiclass case.
`pROC::roc()` has an argument called `direction = "auto"` that "automatically" decides if binary class probabilities like `0.8` are to be interpreted as "the probability that this observation is a control" or "the probability that this observation is an event". It generally chooses the right thing, _however_ it "decides" by computing the median probability of each group (case / control) and takes the probability that is higher. This is not always correct, especially when resampling or computing a metric that calls the binary version of …
=> Fix ROC AUC direction and handling of levels with zero occurrences

R/prob-gain_curve.R, tests/testthat/test_autoplot.R
Closes #192
This resolves issue #192 by plotting the lines on top of the boundary polygon for the gain curve.
=> Plot lines on top of polygon for gain curve

NEWS.md, R/class-bal_accuracy.R, R/class-j_index.R, R/class-npv.R, R/class-ppv.R, tests/testthat/test-class-ppv-warning-binary.txt, tests/testthat/test-class-ppv.R
Closes #101 
Follow up to #118 where this should have been done originally
Any time we compute a sens + spec type of metric, we used to use `recall_binary()` because it was the same as computing sens. In #118 we added `sens_binary()` so we could throw sens specific warnings as needed, but our usage of `recall_binary()` wasn't updated to use `sens_binary()` instead. This PR fixes that.
=> Use `sens_binary()` rather than `recall_binary()` where appropriate

DESCRIPTION, vignettes/metric-types.Rmd
At the cost of a slightly uglier table
=> Drop usage of kableExtra to avoid `collapse_rows()` issue

DESCRIPTION, NAMESPACE, NEWS.md, R/metrics.R, tests/testthat/test-print-metric_set.txt, tests/testthat/test_metrics.R
Added an `as_tibble()` method for `metric_set` objects and used it in the print method (instead of a data.frame). This is for #186.
=> added an `as_tibble()` method for `metric_set`s

NEWS.md, R/conf_mat.R, tests/testthat/test_autoplot.R
Closes #191 
Better fix for #157 
Not sure why we didn't do this to start with in #170 
``` r
foo <- factor(sample(1:5, 100, replace = T))
bar <- factor(sample(1:5, 100, replace = T))
df <- data.frame(foo, bar)
conf <- yardstick::conf_mat(df, foo, bar, dnn = c("custom", "names"))
ggplot2::autoplot(conf, type = "mosaic")
```
``` r
ggplot2::autoplot(conf, type = "heatmap")
```
<sup>Created on 2021-03-25 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
=> Allow custom table names in `autoplot.conf_mat()`

DESCRIPTION, NEWS.md, R/misc.R, R/prob-gain_curve.R, R/prob-lift_curve.R, R/prob-pr_curve.R, R/prob-roc_curve.R, tests/testthat/test-prob-roc.R
Powered by new dplyr 1.0.0 features, i.e. multiple rows returned in a single summarise call, and packed data frame columns.
This is great because now even the curve functions go through the standard `metric_summarizer()` machinery.
=> Remove usage of `dplyr::do()` in favor of `dplyr::summarise()`

NEWS.md, R/misc.R, R/prob-gain_capture.R, R/prob-helpers.R, man/gain_capture.Rd, tests/testthat/helper-macro-prob.R, tests/testthat/test-prob-gain_capture.R, tests/testthat/test-prob-gain_curve.R
And a `yardstick_truth_table()` that some of the other prob metrics will need. Notably, it uses case weights when generating the table so the `"macro_weighted"` averaging weights are correct (verified by a test that expands out the frequency weighted data frame and gets the same result as when weights are supplied)
=> Add case weight support for `gain_capture()`

NEWS.md, R/conf_mat.R, man/conf_mat.Rd, tests/testthat/_snaps/conf_mat.md, tests/testthat/test-conf_mat.R
- Added case weight support to `conf_mat()`
- Had to deprecate support for `...` in `conf_mat()`, which were passed on to `table()` but didn't do anything that was particularly interesting.
=> Add case weight support to `conf_mat()`

NEWS.md, R/metrics.R, R/prob-binary-thresholds.R, R/prob-pr_curve.R, R/prob-roc_auc.R, R/prob-roc_aunp.R, R/prob-roc_aunu.R, R/prob-roc_curve.R, man/metrics.Rd, man/roc_auc.Rd, man/roc_aunp.Rd, man/roc_aunu.Rd, man/roc_curve.Rd, tests/testthat/_snaps/error-handling.md, tests/testthat/_snaps/metrics.md, tests/testthat/_snaps/prob-roc.md, tests/testthat/_snaps/prob-roc_aunp.md, tests/testthat/_snaps/prob-roc_aunu.md, tests/testthat/test-metric-tweak.R, tests/testthat/test-prob-gain_capture.R, tests/testthat/test-prob-roc.R, tests/testthat/test-prob-roc_aunp.R, tests/testthat/test-prob-roc_aunu.R, tests/testthat/test_metrics.R
This is in preparation of a switch to a custom roc-curve implementation that supports case weights.
It will no longer support any of the `options` passed on to pROC, so we have to deprecate that argument. It was present in:
- `roc_curve()`
- `roc_auc()`
- `roc_aunp()`
- `roc_aunu()`
- `metrics()`
Also contains a little cleanup of the pr-curve internals. Extracted `binary_threshold_curve()` for use in roc-curve.
=> Deprecate the `options` argument that is passed on to pROC

DESCRIPTION, NEWS.md
With case weight support, our roc-curve now uses a custom implementation, and we don't use pROC at all anymore
=> Remove the pROC dependency

R/conf_mat.R, tests/testthat/test-conf_mat.R
This is relied on by tune in `tune::conf_mat_resampled()`. It calls `as.data.frame(x$table)` and expects the `as.data.frame.table()` method to be run.
Slightly reverts part of #295
=> Ensure that the underlying object in `conf_mat()` is a classed `<table>`

R/misc.R, R/num-ccc.R, R/prob-binary-thresholds.R, R/prob-gain_curve.R, tests/testthat/test-misc.R, tests/testthat/test-num-ccc.R, tests/testthat/test-prob-gain_curve.R, tests/testthat/test-prob-roc_curve.R
Mainly involves a few key conversions to double.
The alternative is to make the case weights classes in hardhat directly support arithmetic and math operations, but I'm not quite sure we want that. I feel like wrapping the column up in a case weights class has a very specific meaning, and you should unwrap it to make it work more like a double/integer vector again.
=> Ensure that hardhat case weights are supported everywhere

tests/testthat/_snaps/misc.md
The new {rlang} version introduced links in internal errors https://github.com/r-lib/rlang/commit/a72c03c5c9e9d72c94c27082d5298a394577af69. This PR updates the 5 affected snapshots
=> update snapshot of internal yardstick_table

DESCRIPTION
The changes made in https://github.com/tidymodels/yardstick/pull/322 uses tidyselect 1.2.0 features. This was not reflected in the required version denoted by the DESCRIPTION file. This PR fixes that
=> depend on tidyselect 1.2.0

NEWS.md, R/prob-pr_curve.R
All of our probability curve `autoplot()` methods use an aspect ratio of 1.00 except PR curves. They all have aces that are on 0:1 and it makes sense to keep them squares.
=> consistent aspect ratio for PR curves

NEWS.md, R/event-level.R, tests/testthat/_snaps/event-level.md, tests/testthat/test-event-level.R, tests/testthat/test-global-option.R
This PR hard deprecates the `yardstick.event first` global option. Setting it will no longer do anything, except throw a warning, reminding the user that setting the option doesn't do anything.
Revdep check was run on this PR and it didn't break anything.
=> Hard deprecate yardstick.event first

tests/testthat/_snaps/aaa-new.md, tests/testthat/_snaps/autoplot.md, tests/testthat/_snaps/error-handling.md, tests/testthat/_snaps/flatten.md, tests/testthat/_snaps/metric-tweak.md, tests/testthat/_snaps/metrics.md, tests/testthat/_snaps/num-huber_loss.md, tests/testthat/_snaps/num-mase.md, tests/testthat/_snaps/num-pseudo_huber_loss.md, tests/testthat/_snaps/prob-classification_cost.md, tests/testthat/_snaps/prob-roc_aunp.md, tests/testthat/_snaps/prob-roc_aunu.md, tests/testthat/_snaps/prob-roc_curve.md, tests/testthat/test-aaa-new.R, tests/testthat/test-autoplot.R, tests/testthat/test-error-handling.R, tests/testthat/test-flatten.R, tests/testthat/test-metric-tweak.R, tests/testthat/test-metrics.R, tests/testthat/test-num-huber_loss.R, tests/testthat/test-num-mase.R, tests/testthat/test-num-pseudo_huber_loss.R, tests/testthat/test-prob-classification_cost.R, tests/testthat/test-prob-gain_curve.R, tests/testthat/test-prob-lift_curve.R, tests/testthat/test-prob-roc_aunp.R, tests/testthat/test-prob-roc_aunu.R, tests/testthat/test-prob-roc_curve.R
This PR removes all uses of `expect_error()` with `expect_no_error()` or `expect_snapshot()`
to close https://github.com/tidymodels/yardstick/issues/335
=> No more expect_error()

NEWS.md, R/conf_mat.R, tests/testthat/_snaps/conf_mat.md, tests/testthat/test-conf_mat.R
This PR aims to close https://github.com/tidymodels/yardstick/issues/327, close https://github.com/tidymodels/yardstick/issues/314, and close https://github.com/tidymodels/yardstick/issues/234.
Users were getting internal errors when using `conf_mat()` incorrectly. This happened because the `conf_mat()` functions called `yardstick_table()` directly without doing any input checking.
This PR fixes that by adding the function `conf_mat_impl()` that is used internally in `conf_mat.data.frame()` and `conf_mat.grouped_df()` such that we can do input checking correctly.
=> Add conf_mat_impl()

NEWS.md, R/aaa.R
``` r
```
<sup>Created on 2023-02-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
``` r
#> For binary classification, the first factor level is assumed to be the event.
#> Use the argument `event_level = "second"` to alter this as needed.
```
<sup>Created on 2023-02-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
=> No more startup message

R/misc.R, tests/testthat/_snaps/misc.md, tests/testthat/test-misc.R
This PR adds the internal function `trapezoidal_rule()`, that will be used in the future metrics `integrated_brier_score()` and `survival_roc_auc()`
=> Add trapezoidal_rule() helper function

NEWS.md, R/metrics.R, man/metric_set.Rd, tests/testthat/_snaps/metrics.md, tests/testthat/test-metrics.R
To close https://github.com/tidymodels/yardstick/issues/398
``` r
library(survival)
survival_metrics <- metric_set(
brier_survival_integrated,
roc_auc_survival,
concordance_survival
)
lung_surv |>
survival_metrics(
truth = surv_obj,
estimate = .pred_survival,
censoring_weights = ipcw,
eval_time = .time
)
#> # A tibble: 3 × 3
#>   .metric                   .estimator .estimate
#>   <chr>                     <chr>          <dbl>
#> 1 brier_survival_integrated standard       0.156
#> 2 roc_auc_survival          standard       0.867
#> 3 concordance_survival      standard       0.542
survival_metrics <- metric_set(
brier_survival,
brier_survival_integrated,
roc_auc_survival,
concordance_survival
)
lung_surv |>
survival_metrics(
truth = surv_obj,
estimate = .pred_survival, …
```
=> Survival metric set

R/surv-roc_survival_curve.R
Before this PR, I saw:
``` r
bench::mark(
yardstick:::roc_curve_survival_impl(
truth = rr_churn_data$surv,
estimate = rr_churn_data$surv_prob,
censoring_weights = rr_churn_data$ipcw,
eval_time = rr_churn_data$times
)
)
#> # A tibble: 1 × 13
#>   expression    min median itr/s…¹ mem_a…² gc/se…³ n_itr  n_gc total…⁴ result
#>   <list>     <bch:> <bch:>   <dbl> <bch:b>   <dbl> <int> <dbl> <bch:t> <list>
#> 1 <chr [1]>   50.6s  50.6s  0.0198   133GB    13.7     1   694   50.6s <tibble>
#> # … with 3 more variables: memory <list>, time <list>, gc <list>, and
#> #   abbreviated variable names ¹​`itr/sec`, ²​mem_alloc, ³​`gc/sec`, ⁴​total_time
#> # ℹ Use `colnames()` to see all variable names
```
With this PR:
``` r
#> # A tibble: 1 × 13
#>   expression    min median itr/s…¹ mem_a…² gc/se…³ n_itr …
```
=> speed up `roc_curve_survival_impl()`

R/surv-brier.R, R/template.R, tests/testthat/test-surv-brier.R, tests/testthat/test-surv-brier_integrated.R
To close https://github.com/tidymodels/yardstick/issues/397
Now all arguments related to evaluation time uses `eval_time` and all output uses the name `.eval_time`.
=> Update naming evaluation time

R/aaa-new.R, R/class-kap.R, R/class-precision.R, R/class-recall.R, R/class-sens.R, R/class-spec.R, R/conf_mat.R, R/deprecated-prob_helpers.R, R/deprecated-template.R, R/estimator-helpers.R, R/event-level.R, R/import-standalone-survival.R, R/metric-tweak.R, R/metrics.R, R/misc.R, R/num-huber_loss.R, R/num-mase.R, R/num-pseudo_huber_loss.R, R/prob-brier.R, R/prob-classification_cost.R, R/prob-gain_curve.R, R/prob-helpers.R, R/prob-lift_curve.R, R/prob-pr_curve.R, R/prob-roc_auc.R, R/prob-roc_curve.R, R/surv-roc_curve_survival.R, R/template.R
Both {rlang} and {vctrs} are imported. So I'm going to make this change to remove some visual clutter in the codebase
=> Don't namespace functions from rlang or vctrs

tests/testthat/test-prob-average_precision.R
{waldo} now sees `NaN` and `NA_real_` as different, so this PR corrects the expected result
=> correct expected result

DESCRIPTION, R/template.R, tests/testthat/test-template.R
In tune, `yardstick_eval_select()` is called `n_resamples * n_grid_points * n_metrics` times for each column selection input. Within a tuning process, the `expr` passed to `eval_select()` uniquely identifies the selection result. We can thus cache those known selections after they're evaluated once and then retrieve them for the remainder of the tuning process. 
In context, this can have a substantial impact on time to evaluate against resamples, especially with quick model fits and many resamples / grid points. With this PR:
``` r
bench::mark(
new = 
fit_resamples(
logistic_reg(),
Class ~ .,
bootstraps(two_class_dat, 1000)
)
)
#> # A tibble: 1 × 13
#>   expression      min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
#>   <bch:expr> <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> …
```
=> cache known selections while tuning

R/aaa-metrics.R, R/fair-aaa.R, man/new_groupwise_metric.Rd, tests/testthat/_snaps/aaa-metrics.md, vignettes/grouping.Rmd
=> add vignette on group-aware and -wise behavior

R/surv-roc_auc_survival.R, R/surv-roc_curve_survival.R, tests/testthat/test-surv-roc_auc_survival.R, tests/testthat/test-surv-roc_curve_survival.R
This PR adds `case_weights` support for survival ROC curve calculations, `roc_curve_survival()` and `roc_auc_survival()`.
This addition in modeled after the way we incorporate case weights for normal ROC curve calculations, as wee here: https://github.com/tidymodels/yardstick/blob/main/R/prob-binary-thresholds.R.
``` r
library(dplyr)
res <- lung_surv %>%
roc_curve_survival(
truth = surv_obj,
.pred
)
wts_res <- lung_surv %>%
mutate(wts = hardhat::frequency_weights(rep(1:0, c(128, 100)))) %>%
roc_curve_survival(
truth = surv_obj,
.pred, 
case_weights = wts
)
identical(res, wts_res)
#> [1] FALSE
subset_res <- lung_surv %>%
slice(1:128) %>%
roc_curve_survival(
truth = surv_obj,
.pred
)
identical(subset_res, wts_res)
#> [1] TRUE
```
=> use case_weights in roc_curve calculations

NEWS.md, R/surv-brier_survival_integrated.R, tests/testthat/_snaps/surv-brier_survival_integrated.md, tests/testthat/test-surv-brier_survival_integrated.R
To close #460
``` r
library(censored)
lung_surv <- lung %>% 
dplyr::mutate(surv = Surv(time, status), .keep = "unused")
cox <- proportional_hazards() %>% 
fit(surv ~ ., data = lung_surv)
pred <- augment(cox, lung_surv, eval_time = 10)
brier_survival_integrated(
data = pred,
truth = surv,
.pred
)
#> Error in `brier_survival_integrated()`:
#> ! At least 2 evaluation time is required. Only 1 unique time was given.
```
=> throw error for single eval time in brier_survival_integrated()

R/surv-brier_survival_integrated.R, R/validation.R, tests/testthat/_snaps/validation.md, tests/testthat/test-validation.R
To close https://github.com/tidymodels/yardstick/issues/469
=> Validate that all the `.eval_time` columns are identical

R/surv-brier_survival.R, R/surv-brier_survival_integrated.R, R/surv-concordance_survival.R, R/surv-roc_auc_survival.R, R/surv-roc_curve_survival.R, _pkgdown.yml, man/brier_survival.Rd, man/brier_survival_integrated.Rd, man/concordance_survival.Rd, man/roc_auc_survival.Rd, man/roc_curve_survival.Rd
This PR:
- removed `@keywords internal` from all survival metrics
- added them back to the pkgdown
to close #478
=> Bring survival metrics back back

DESCRIPTION, R/fair-demographic_parity.R, R/fair-equal_opportunity.R, man/demographic_parity.Rd, man/equal_opportunity.Rd
To close https://github.com/tidymodels/yardstick/issues/463
@simonpcouch can you verify that this has been fixed?
=> Fix formatting of example code in fairness metrics pkgdown docs

NEWS.md, R/template.R, tests/testthat/_snaps/template.md, tests/testthat/test-template.R
To close https://github.com/tidymodels/yardstick/issues/443
Before:
``` r
roc_curve(two_class_example, truth = truth, estimate = Class1)
#> Error in `roc_curve()`:
#> ! Can't rename variables in this context.
```
Now:
``` r
roc_curve(two_class_example, truth = truth, estimate = Class1)
#> Error in `roc_curve()`:
#> ✖ This metric doesn't use the `estimate` argument.
#> ℹ Specify the columns without `estimate = `.
```
=> Pretty error on wrongly use of estimate argument

NEWS.md, R/prob-gain_curve.R, R/prob-pr_curve.R, R/prob-roc_curve.R, R/surv-roc_curve_survival.R, tests/testthat/_snaps/template.md, tests/testthat/test-template.R
=> throw warnings when na_rm = FALSE and missing is found in curve metrics

R/fair-aaa.R, R/prob-mn_log_loss.R, man/mn_log_loss.Rd, man/new_groupwise_metric.Rd
Few small typos :)
didn't spot any instances of "its" -> "it's"
=> "it's" -> "its" when applicable in R/ and man/

R/aaa-metrics.R, R/aaa-new.R, R/conf_mat.R, R/metric-tweak.R, R/misc.R, R/prob-helpers.R, R/prob-roc_auc.R, R/prob-roc_curve.R, tests/testthat/_snaps/aaa-metrics.md, tests/testthat/_snaps/aaa-new.md, tests/testthat/_snaps/class-bal_accuracy.md, tests/testthat/_snaps/metric-tweak.md, tests/testthat/_snaps/prob-roc_curve.md, tests/testthat/_snaps/probably.md, tests/testthat/test-class-bal_accuracy.R
This PR passes the calls around in all missing cases, expect for `weighted_table()` which will be tracked with https://github.com/tidymodels/yardstick/issues/521
=> pass calls around

R/aaa-metrics.R, R/class-mcc.R, R/misc.R, R/prob-binary-thresholds.R, R/prob-helpers.R, R/prob-roc_auc.R, R/template.R, tests/testthat/_snaps/aaa-metrics.md, tests/testthat/_snaps/conf_mat.md, tests/testthat/_snaps/estimator-helpers.md, tests/testthat/_snaps/event-level.md, tests/testthat/_snaps/misc.md, tests/testthat/_snaps/num-mase.md, tests/testthat/_snaps/prob-gain_curve.md, tests/testthat/_snaps/prob-pr_curve.md, tests/testthat/_snaps/template.md, tests/testthat/_snaps/validation.md, tests/testthat/test-aaa-metrics.R, tests/testthat/test-conf_mat.R, tests/testthat/test-estimator-helpers.R, tests/testthat/test-event-level.R, tests/testthat/test-misc.R, tests/testthat/test-num-mase.R, tests/testthat/test-prob-gain_curve.R, tests/testthat/test-prob-pr_curve.R, tests/testthat/test-template.R, tests/testthat/test-validation.R
All errors are now snapshotted whenever possible, otherwise they are labeled as unreachable
=> All snapshots

tests/testthat/_snaps/misc.md, tests/testthat/test-misc.R
this test is redundant because we test for this many times other places
=> delete meaningless test

NEWS.md, R/num-poisson_log_loss.R, tests/testthat/test-num-poisson_log_loss.R
To close https://github.com/tidymodels/yardstick/issues/513
This approach is alligned with other implementations by using a small `eps` to avoid `log(0)`
- https://pytorch.org/docs/stable/generated/torch.nn.PoissonNLLLoss.html
- https://github.com/yanyachen/MLmetrics/blob/master/R/Count.R#L17
``` r
yardstick::poisson_log_loss(mtcars, gear, vs)
#> # A tibble: 1 × 3
#>   .metric          .estimator .estimate
#>   <chr>            <chr>          <dbl>
#> 1 poisson_log_loss standard         Inf
yardstick::poisson_log_loss_vec(mtcars$gear, mtcars$vs)
#> [1] Inf
```
``` r
yardstick::poisson_log_loss(mtcars, gear, vs)
#> # A tibble: 1 × 3
#>   .metric          .estimator .estimate
#>   <chr>            <chr>          <dbl>
#> 1 poisson_log_loss standard        72.3 …
```
=> avoid log(0) in poisson_log_loss()

NEWS.md, R/aaa-metrics.R, R/aaa-new.R, tests/testthat/test-aaa-metrics.R
to close https://github.com/tidymodels/yardstick/issues/536
``` r
library(dplyr)
data(hpc_cv)
hpc_cv$obs <- as.ordered(hpc_cv$obs)
cls_mtr <- metric_set(ranked_prob_score, brier_class, kap, roc_auc)
cls_mtr(hpc_cv, obs, VF:L, estimate = pred)
#> # A tibble: 4 × 3
#>   .metric           .estimator .estimate
#>   <chr>             <chr>          <dbl>
#> 1 kap               multiclass    0.508 
#> 2 ranked_prob_score multiclass    0.0857
#> 3 brier_class       multiclass    0.211 
#> 4 roc_auc           hand_till     0.829
```
<sup>Created on 2025-03-11 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
=> Ordered metrics in matric sets
