tidymodels/yardstick

.travis.yml, NEWS.md, R/prob-roc_auc.R, tests/testthat/test-prob-roc.R
=> Call `pROC::auc()` directly

R/class-f_meas.R
=> add beta to matrix method

NEWS.md, R/prob-mn_log_loss.R, tests/testthat/test-prob-mn_log_loss.R
=> Use min/max method when computing `mn_log_loss()`

DESCRIPTION, NEWS.md, R/conf_mat.R, tests/testthat/test_autoplot.R
@apreshill
Maybe @EmilHvitfeldt could look at my changes to the mosaic plot to verify that this was the right approach.
=> closes #130

R/conf_mat.R, tests/testthat/test_autoplot.R
=> Force default labels on confusion matrix for heatmap plot

R/conf_mat.R
Fixes https://github.com/tidymodels/yardstick/issues/158
=> Fix autoplot() mosaic plot column widths

R/metrics.R, tests/testthat/test_metrics.R
Closes #181 
New error:
``` r
library(Metrics)
metric_set(rmse)
#> Error: 
#> The combination of metric functions must be:
#> - only numeric metrics
#> - a mix of class metrics and class probability metrics
#> 
#> The following metric function types are being mixed:
#> - other (rmse <namespace:Metrics>)
```
<sup>Created on 2021-03-25 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
=> Ensure that `validate_function_class()` catches single invalid functions

DESCRIPTION, NEWS.md, R/class-precision.R, R/class-recall.R, R/class-sens.R, R/class-spec.R, R/conditions.R
=> Update `.subclass` to `class` and require rlang 0.4.2

NEWS.md, tests/testthat/_snaps/error-handling.md, tests/testthat/_snaps/numeric.md, tests/testthat/_snaps/prob-roc_aunp.md, tests/testthat/_snaps/prob-roc_aunu.md, tests/testthat/test-error-handling.R, tests/testthat/test-numeric.R, tests/testthat/test-prob-roc_aunp.R, tests/testthat/test-prob-roc_aunu.R
=> Use `expect_snapshot()` to avoid hardcoding `"dplyr_error"`

NEWS.md, R/class-j_index.R, tests/testthat/_snaps/class-j_index.md, tests/testthat/test-class-j_index.R
=> Remove `NA`s from weighted average computation in `j_index()`

DESCRIPTION, NEWS.md, man/yardstick-package.Rd
=> Change maintainer to Emil

R/prob-pr_auc.R, man/average_precision.Rd, man/brier_class.Rd, man/classification_cost.Rd, man/developer-helpers.Rd, man/gain_capture.Rd, man/gain_curve.Rd, man/lift_curve.Rd, man/metrics.Rd, man/mn_log_loss.Rd, man/pr_auc.Rd, man/pr_curve.Rd, man/roc_auc.Rd, man/roc_curve.Rd
=> be more precise in documentation of ... in prob functions

R/template.R
=> use dplyr::pick function

R/metrics.R, tests/testthat/test-metrics.R
Make metric_set() work with dynamic survival metrics()
=> Survival metric set()

vignettes/metric-types.Rmd
to close https://github.com/tidymodels/yardstick/issues/402
=> update vignette/metric-types.Rmd with survival metrics

tests/testthat/test-template.R
This came up when I was working on https://github.com/tidymodels/yardstick/pull/405, and realized that we don't test the output of what happens when you pass in grouped data
=> test that metric summarizer functions works with grouped data

DESCRIPTION, R/aaa-metrics.R, R/aaa-new.R, R/estimator-helpers.R, R/event-level.R, R/fair-aaa.R, R/import-standalone-obj-type.R, R/import-standalone-types-check.R, R/metric-tweak.R, R/prob-helpers.R, R/template.R, tests/testthat/_snaps/aaa-metrics.md, tests/testthat/_snaps/metric-tweak.md
This is the first of 3 (🤞) PRs to move from {rlang} functions to {cli} functions. This PR handles all the non-metric, non-`validation.R` and non-`misc.R`
=> move infrastructure errors to cli

vignettes/metric-types.Rmd
=> Correct minor typo in metric-types.Rmd

R/surv-roc_auc_survival.R, man/roc_auc_survival.Rd, vignettes/metric-types.Rmd
to close https://github.com/tidymodels/yardstick/issues/427
The original issue was that a line wasn't deleted when it should have been.
=> fix survival metrics argument documentation

R/class-precision.R, R/class-recall.R, R/class-sens.R, R/class-spec.R, tests/testthat/_snaps/class-f_meas.md, tests/testthat/_snaps/class-j_index.md, tests/testthat/_snaps/class-ppv.md, tests/testthat/_snaps/class-precision.md, tests/testthat/_snaps/class-recall.md, tests/testthat/_snaps/class-sens.md, tests/testthat/_snaps/class-spec.md
=> transition "occured" -> "occurred"

R/aaa-metrics.R
to close https://github.com/tidymodels/yardstick/issues/447
=> don't use deprecated vars_select()

R/aaa-metrics.R, man/metrics.Rd
=> link to metric_set() from metrics()

R/surv-brier_survival.R, man/brier_survival.Rd, man/brier_survival_integrated.Rd, man/roc_auc_survival.Rd, man/roc_curve_survival.Rd
=> fix documentation of estimate argument for dynamic metrics _vec() versions

NEWS.md, R/class-sens.R, man/average_precision.Rd, man/bal_accuracy.Rd, man/classification_cost.Rd, man/detection_prevalence.Rd, man/f_meas.Rd, man/gain_capture.Rd, man/gain_curve.Rd, man/j_index.Rd, man/lift_curve.Rd, man/mn_log_loss.Rd, man/npv.Rd, man/ppv.Rd, man/pr_auc.Rd, man/pr_curve.Rd, man/precision.Rd, man/recall.Rd, man/roc_auc.Rd, man/roc_curve.Rd, man/sens.Rd, man/spec.Rd, man/summary.conf_mat.Rd
close https://github.com/tidymodels/yardstick/issues/432
=> Update documentation of event_level

DESCRIPTION, NEWS.md, R/surv-brier_survival.R, README.Rmd, README.md, cran-comments.md, man/brier_survival.Rd, man/brier_survival_integrated.Rd, man/roc_auc_survival.Rd, man/roc_curve_survival.Rd, revdep/README.md, revdep/cran.md, revdep/problems.md
to close https://github.com/tidymodels/yardstick/issues/492
=> Release Candidate 1.3.0
